=== olegkordun/multi-module-camel-mq/integration-test/src/test/resources/test-data/xml/dataset.dtd
<!ELEMENT dataset (

    company*,
    users*,
    user_role*)>

<!ELEMENT company EMPTY>
<!ATTLIST company
    id CDATA #REQUIRED
    category CDATA #REQUIRED
    details CDATA #REQUIRED
    email CDATA #REQUIRED
    info CDATA #REQUIRED
    name CDATA #REQUIRED
    phone CDATA #IMPLIED
    status CDATA #REQUIRED
>


<!ELEMENT schema_version EMPTY>
<!ATTLIST schema_version
    version_rank CDATA #REQUIRED
    installed_rank CDATA #REQUIRED
    version CDATA #REQUIRED
    description CDATA #REQUIRED
    type CDATA #REQUIRED
    script CDATA #REQUIRED
    checksum CDATA #IMPLIED
    installed_by CDATA #REQUIRED
    installed_on CDATA #IMPLIED
    execution_time CDATA #REQUIRED
    success CDATA #REQUIRED
>

<!ELEMENT users EMPTY>
<!ATTLIST users
    id CDATA #REQUIRED
    comment CDATA #IMPLIED
    email CDATA #REQUIRED
    firstname CDATA #IMPLIED
    lastname CDATA #IMPLIED
    password CDATA #REQUIRED
    company_id CDATA #IMPLIED
    username CDATA #IMPLIED
>

<!ELEMENT user_role EMPTY>
<!ATTLIST user_role
    user_id CDATA #REQUIRED
    role_name CDATA #REQUIRED
>

=== olegkordun/multi-module-camel-mq/integration-test/src/test/resources/test-data/xml/three-companies.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "dataset.dtd">
<dataset>

    <company id="1" category="LOW_RISK" details="Some details one"
             email="emailone@email.ru" info="Some info one" name="Some one NAME" phone="123123 one"
             status="ACTIVE"/>
    <company id="2" category="HIGHT_RISK" details="Some details two"
             email="emailtwo@email.ru" info="Some info two" name="Some NAME two" phone="123123 two"
             status="ACTIVE"/>
    <company id="3" category="HIGHT_RISK" details="Some details 3"
             email="email3@email.ru" info="Some info 3" name="Some NAME 3" phone="11231231" status="BLOCKED"/>
    <users id="1" email="asd@asd.ru"
           password="a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3"
           firstname="firstname" lastname="lastname" comment="comment" username="user"/>
    <users id="2" email="asd@asd.ru"
           password="a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3"
           firstname="firstname" lastname="lastname" comment="comment" username="admin"/>
    <user_role user_id="1" role_name="ROLE_USER"/>
    <user_role user_id="1" role_name="ROLE_COMPANYUSER"/>
    <user_role user_id="2" role_name="ROLE_USER"/>
    <user_role user_id="2" role_name="ROLE_ADMIN"/>
</dataset>
